# http://localhost:8080

# http://localhost:8080/students

POST http://localhost:8080/students HTTP/1.1
content-type: application/json

{
  "Id": 0,
  "Name": "New Student Name Prevent",
  "Surname": "New Student Lastname SQL injection",
  "Code": "",
  "Grade": "",
  "Birthdate": "1990-08-29T00:00:00Z",
  "PublicId": "",
  "Photo": ""
}